### PR TITLE
Add instructions for starting the demo

### PR DESCRIPTION
**Pull request by jmacarthur**

### CODE REVIEW

**Comment by devcurmudgeon** [comment]
+1 but would it make sense to have the CodethinkLabs version be upstream, rather than a fork?

**Comment by jmacarthur** [comment]
This is an experiment and I don't know how long it'll be around for, but yes

**Comment by ssssam** [comment]
it probably does make sense to move to codethinklabs, we can always delete the repo if it gets superceded by a better tool

**Comment by jmacarthur** [comment]
Then let's just treat https://github.com/codethinklabs/software-dependency-visualizer as upstream from now on.

**Comment by devcurmudgeon** [comment]
I think it's not that simple... because this is the original, afaict github has Issues pointed here, but not to the codethinklabs version?

**Comment by palvarez89** [comment]
I fixed that, now https://github.com/CodethinkLabs/software-dependency-visualizer is the canonical place, and we should probably deprecate this one.

**Pull request merged**
